POST http://localhost:3000/new HTTP/1.1
content-type: application/json

{
    "name": "Geralt",
    "power": 20,
    "provision": 10 ,
    "faction": "Neutral",
    "type": "Witcher"
}

### 
http://localhost:3000/cards

### 
http://localhost:3000/cards/63fe2fdb510fdf3690f6386f

###
PATCH http://localhost:3000/cards/63fe2fdb510fdf3690f6386e HTTP/1.1
content-type: application/x-www-form-urlencoded

{
    "name": "Geralt 123",
    "power": 20,
    "provision": 10 ,
    "faction": "Neutral",
    "type": "Witcher"
}

###

POST http://localhost:3000/?a=b&abc=bb HTTP/1.1
content-type: application/x-www-form-urlencoded
